# golangci-lint configuration for Kite
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced Go linter
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused code
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import statements
    - misspell      # Finds commonly misspelled words
    - unparam       # Finds unused function parameters
    - unconvert     # Removes unnecessary type conversions
    - goconst       # Finds repeated strings that could be constants
    - gocyclo       # Computes cyclomatic complexities
    - dupl          # Code clone detection
    - gosec         # Security problems
    - revive        # Fast, configurable, extensible linter
    - prealloc      # Finds slice declarations that could be preallocated
    - exportloopref # Checks for pointers to enclosing loop variables
    - nilerr        # Finds code that returns nil even if it checks that the error is not nil

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: confusing-naming
        severity: warning
      - name: empty-block
        severity: warning
      - name: superfluous-else
        severity: warning
      - name: var-naming
        severity: warning
      - name: unexported-return
        severity: warning

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path provided as taint input (common in file operations)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Exclude generated files
    - path: '\.pb\.go$'
      linters:
        - all

    # Exclude vendor directory
    - path: vendor/
      linters:
        - all
