apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kite
  namespace: kite
  labels:
    app: kite
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kite
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - kite

