apiVersion: v1
kind: Service
metadata:
  name: kite
  namespace: kite
  labels:
    app: kite
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kite
  sessionAffinity: None

