jurisdiction: EU
document_types:
  contract:
    required_fields:
      - party_names
      - signatures
      - effective_date
      - governing_law
    risk_flags:
      - missing_signatures
      - outdated_clauses
      - missing_governing_law
  statute:
    required_fields:
      - statute_number
      - enactment_date
      - authority
    risk_flags:
      - missing_statute_number
languages:
  - en
  - fr
  - de
  - es
notes: >
  The European Union has a civil law tradition with harmonized regulations 
  across member states. Contracts often include governing law and jurisdiction 
  clauses. Multilingual support is essential due to the diversity of official 
  EU languages. Statutes and directives are key document types.