"""Application constants."""

# HTTP
DEFAULT_TIMEOUT = 30
DEFAULT_USER_AGENT = "Kite/2.0 Legal Case Scraper"
MAX_RETRIES = 3
RETRY_BACKOFF = 0.3

# Rate limiting
DEFAULT_RATE_LIMIT = 1.0  # requests per second
RATE_LIMIT_WAIT = 1.0

# Cache
DEFAULT_CACHE_TTL = 300  # seconds
MAX_CACHE_SIZE = 1000

# Scraping
DEFAULT_RESULTS_LIMIT = 20
MAX_RESULTS_LIMIT = 100

# Pagination
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 50

# Timeouts
SCRAPER_TIMEOUT = 60
CONNECTION_TIMEOUT = 10
READ_TIMEOUT = 30
