jurisdiction: US
document_types:
  contract:
    required_fields:
      - party_names
      - signatures
      - effective_date
    risk_flags:
      - missing_signatures
      - outdated_clauses
  court_decision:
    required_fields:
      - case_number
      - judge
      - decision_date
    risk_flags:
      - missing_case_number
languages:
  - en
notes: >
  The United States operates under a federal common law system with 
  significant state-level legal variation. Contracts and court decisions 
  often require explicit party identification, signatures, and effective 
  dates. Risk flagging is important for missing signatures and outdated 
  clauses, especially due to frequent regulatory updates.