name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install black flake8 mypy isort
    - name: Run black
      run: black --check kite/ tests/
    - name: Run flake8
      run: flake8 kite/ tests/
    - name: Run isort
      run: isort --check-only kite/ tests/
    - name: Run mypy
      run: mypy kite/
